# Generated by Django 4.2.9 on 2024-02-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mypublish",
            name="photo",
        ),
    ]
